version: '3.4'

services:
  inventory:
    image: inventory
    build:
      context: .
      dockerfile: ./inventory/Dockerfile
    environment:
      NODE_ENV: dev
      PORT: 3001
      MICROSERVICE_NAME: inventory
    ports:
      - 3001:3001
  shopping:
    image: shopping
    build:
      context: .
      dockerfile: ./shopping/Dockerfile
    environment:
      NODE_ENV: dev
      PORT: 3000
      MICROSERVICE_NAME: shopping
    ports:
      - 3000:3000      
  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net
networks:
  rabbitmq_net:
    driver: bridge            